version: 2.1
orbs:
  python: circleci/python@2.0.3

jobs:
  build_and_test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          working_directory: ~/test/
          command: python -m unittest

workflows:
  test_my_app:
    jobs:
      - build_and_test
